name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

      - name: Warm Go proxy for pkg.go.dev
        run: |
          # Extract tag from GITHUB_REF
          TAG=${GITHUB_REF#refs/tags/}
          echo "Warming Go proxy for tag: $TAG"

          # Trigger pkg.go.dev indexing by warming the Go proxy
          curl -f "https://proxy.golang.org/github.com/dmikushin/apkext/@v/${TAG}.info" || echo "Primary proxy warming failed, continuing..."

          # Alternative warming using go list
          GOPROXY=proxy.golang.org go list -m "github.com/dmikushin/apkext@${TAG}" || echo "Secondary proxy warming failed, continuing..."

          echo "Go proxy warming completed"